// preload.cjs — безопасный мост UI ↔ main (contextIsolation).
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('prizrak', {
  config: (a) => ipcRenderer.invoke('config', a),
  bootstrap: () => ipcRenderer.invoke('bootstrap'),
  // 🛡 Призрак-VPN: оплата 👻 → тап по стране → туннель. Конфигов нет.
  vpn: {
    status: () => ipcRenderer.invoke('vpn-status'),
    sub: () => ipcRenderer.invoke('vpn-sub'),
    subscribe: (months) => ipcRenderer.invoke('vpn-subscribe', { months }),
    connect: (country) => ipcRenderer.invoke('vpn-connect', { country }),
    maskOff: () => ipcRenderer.invoke('vpn-mask-off'),
    nodeOn: () => ipcRenderer.invoke('vpn-node-on'),
    nodeOff: () => ipcRenderer.invoke('vpn-node-off'),
  },
  vpnCountries: () => ipcRenderer.invoke('vpn-countries'),
  rendererReady: () => ipcRenderer.invoke('renderer-ready'),
  register: (a) => ipcRenderer.invoke('register', a),
  login: (a) => ipcRenderer.invoke('login', a),
  logout: () => ipcRenderer.invoke('logout'),
  whoami: () => ipcRenderer.invoke('whoami'),
  persistUI: (blob) => ipcRenderer.invoke('persist-ui', blob),
  loadUI: () => ipcRenderer.invoke('load-ui'),
  sendDirect: (a) => ipcRenderer.invoke('send-direct', a),
  forwardAttachment: (a) => ipcRenderer.invoke('forward-attachment', a),
  getPrivacy: () => ipcRenderer.invoke('privacy-get'),
  setPrivacy: (a) => ipcRenderer.invoke('privacy-set', a),
  giftCatalog: () => ipcRenderer.invoke('gift-catalog'),
  giftSend: (a) => ipcRenderer.invoke('gift-send', a),
  giftsOf: (a) => ipcRenderer.invoke('gifts-of', a),
  giftsMine: () => ipcRenderer.invoke('gifts-mine'),
  giftConvert: (a) => ipcRenderer.invoke('gift-convert', a),
  giftHide: (a) => ipcRenderer.invoke('gift-hide', a),
  markRead: (a) => ipcRenderer.invoke('mark-read', a),
  markReceived: (a) => ipcRenderer.invoke('mark-received', a),
  mediaEnsure: (a) => ipcRenderer.invoke('media-ensure', a),
  mediaHead: (a) => ipcRenderer.invoke('media-head', a),
  mediaFederate: (a) => ipcRenderer.invoke('media-federate', a),
  mediaPushStatus: (a) => ipcRenderer.invoke('media-push-status', a),
  createGroup: (a) => ipcRenderer.invoke('create-group', a),
  createChannel: (a) => ipcRenderer.invoke('create-channel', a),
  listRooms: () => ipcRenderer.invoke('list-rooms'),
  roomGet: (a) => ipcRenderer.invoke('room-get', a),
  presence: (a) => ipcRenderer.invoke('presence', a),
  roomJoin: (a) => ipcRenderer.invoke('room-join', a),
  roomLeave: (a) => ipcRenderer.invoke('room-leave', a),
  invite: (a) => ipcRenderer.invoke('invite', a),
  sendRoom: (a) => ipcRenderer.invoke('send-room', a),
  getHistory: (a) => ipcRenderer.invoke('get-history', a),
  getChannelHistory: (a) => ipcRenderer.invoke('channel-history', a),
  channelReactions: (a) => ipcRenderer.invoke('channel-reactions', a),
  channelReact: (a) => ipcRenderer.invoke('channel-react', a),
  channelReactPaid: (a) => ipcRenderer.invoke('channel-react-paid', a),
  reactDirect: (a) => ipcRenderer.invoke('react-direct', a),
  reactPaidDirect: (a) => ipcRenderer.invoke('react-paid-direct', a),
  accountExport: (a) => ipcRenderer.invoke('account-export', a),
  accountPickFile: () => ipcRenderer.invoke('account-pick-file'),
  accountImport: (a) => ipcRenderer.invoke('account-import', a),
  seedEnable: () => ipcRenderer.invoke('seed-enable'),
  seedRecover: (a) => ipcRenderer.invoke('seed-recover', a),
  syncRead: (a) => ipcRenderer.invoke('sync-read', a),
  devicesList: () => ipcRenderer.invoke('devices-list'),
  deviceRevoke: (a) => ipcRenderer.invoke('device-revoke', a),
  roomReactionsSettings: (a) => ipcRenderer.invoke('room-reactions-settings', a),
  attachSend: (a) => ipcRenderer.invoke('attach-send', a),
  attachUpload: (a) => ipcRenderer.invoke('attach-upload', a),
  attachCancel: (a) => ipcRenderer.invoke('attach-cancel', a),
  onUploadProgress: (cb) => ipcRenderer.on('upload-progress', (_e, d) => cb(d)),
  attachFetch: (a) => ipcRenderer.invoke('attach-fetch', a),
  attachCache: (a) => ipcRenderer.invoke('attach-cache', a),
  readFile: (a) => ipcRenderer.invoke('read-file', a),
  attachDownload: (a) => ipcRenderer.invoke('attach-download', a),
  attachCancelDownload: (a) => ipcRenderer.invoke('attach-cancel-download', a),
  attachOpen: (a) => ipcRenderer.invoke('attach-open', a),
  imageWindow: (a) => ipcRenderer.invoke('image-window', a),
  dragOut: (path) => ipcRenderer.send('drag-out', path),
  onDownloadProgress: (cb) => ipcRenderer.on('download-progress', (_e, d) => cb(d)),
  wallet: () => ipcRenderer.invoke('wallet'),
  ghostsHistory: () => ipcRenderer.invoke('ghosts-history'),
  ghostsSend: (a) => ipcRenderer.invoke('ghosts-send', a),
  ghostsBuy: (a) => ipcRenderer.invoke('ghosts-buy', a),
  nodesMine: () => ipcRenderer.invoke('nodes-mine'),
  nodesBind: (a) => ipcRenderer.invoke('nodes-bind', a),
  deleteMessage: (a) => ipcRenderer.invoke('delete-message', a),
  mediaDelete: (a) => ipcRenderer.invoke('media-delete', a),
  roomRole: (a) => ipcRenderer.invoke('room-role', a),
  roomTransfer: (a) => ipcRenderer.invoke('room-transfer', a),
  roomKick: (a) => ipcRenderer.invoke('room-kick', a),
  roomBan: (a) => ipcRenderer.invoke('room-ban', a),
  roomUnban: (a) => ipcRenderer.invoke('room-unban', a),
  roomReadonly: (a) => ipcRenderer.invoke('room-readonly', a),
  safetyStatus: (a) => ipcRenderer.invoke('safety-status', a),
  safetyVerify: (a) => ipcRenderer.invoke('safety-verify', a),
  safetyUnverify: (a) => ipcRenderer.invoke('safety-unverify', a),
  contactShare: (a) => ipcRenderer.invoke('contact-share', a),
  safetyQr: (a) => ipcRenderer.invoke('safety-qr', a),
  getAutostart: () => ipcRenderer.invoke('get-autostart'),
  setAutostart: (a) => ipcRenderer.invoke('set-autostart', a),
  setNotif: (a) => ipcRenderer.invoke('set-notif', a),
  getCloseToTray: () => ipcRenderer.invoke('get-close-to-tray'),
  setCloseToTray: (a) => ipcRenderer.invoke('set-close-to-tray', a),
  setBadge: (a) => ipcRenderer.invoke('set-badge', a),
  netPoke: () => ipcRenderer.invoke('net-poke'),
  setMuted: (a) => ipcRenderer.invoke('set-muted', a),
  openWindow: (a) => ipcRenderer.invoke('open-window', a),
  onFocusChat: (cb) => ipcRenderer.on('focus-chat', (_e, chat) => cb(chat)),
  openExternal: (a) => ipcRenderer.invoke('open-external', a),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  updateState: () => ipcRenderer.invoke('update-state'),
  updateInstall: () => ipcRenderer.invoke('update-install'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, d) => cb(d)),
  getProfile: (a) => ipcRenderer.invoke('get-profile', a),
  setProfile: (a) => ipcRenderer.invoke('set-profile', a),
  setRoomProfile: (a) => ipcRenderer.invoke('set-room-profile', a),
  roomShare: (a) => ipcRenderer.invoke('room-share', a),
  roomDiag: (a) => ipcRenderer.invoke('room-diag', a),
  channelResync: (a) => ipcRenderer.invoke('channel-resync', a),
  joinLink: (a) => ipcRenderer.invoke('join-link', a),
  roomRetention: (a) => ipcRenderer.invoke('room-retention', a),
  roomSettings: (a) => ipcRenderer.invoke('room-settings', a),
  searchGroups: (a) => ipcRenderer.invoke('groups-search', a),
  adminStorageGet: () => ipcRenderer.invoke('admin-storage-get'),
  adminStorageSet: (a) => ipcRenderer.invoke('admin-storage-set', a),
  callStart: (a) => ipcRenderer.invoke('call-start', a),
  callAccept: (a) => ipcRenderer.invoke('call-accept', a),
  callMedia: (a) => ipcRenderer.invoke('call-media', a),
  callPliRequest: () => ipcRenderer.invoke('call-pli-request'),
  callHangup: () => ipcRenderer.invoke('call-hangup'),
  onRealtime: (cb) => ipcRenderer.on('realtime', (_e, ev) => cb(ev)),
  onIncomingCall: (cb) => ipcRenderer.on('incoming-call', (_e, ev) => cb(ev)),
  onCallMedia: (cb) => ipcRenderer.on('call-media', (_e, d) => cb(d)),
  onCallRaw: (cb) => ipcRenderer.on('call-raw', () => cb()),
  onCallPli: (cb) => ipcRenderer.on('call-pli', () => cb()),
  onOpenedRoom: (cb) => ipcRenderer.on('opened-room', (_e, room) => cb(room)),
  onOpenedDm: (cb) => ipcRenderer.on('opened-dm', (_e, userId) => cb(userId)),
  onDeeplinkError: (cb) => ipcRenderer.on('deeplink-error', (_e, msg) => cb(msg)),
});
